[package]
name = "v5_core"
description = "Vex V5 robot serial port accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4"
crc = "3"
libloading = "0.8"
log = "0.4"
serde = "1"
serialport = "4"
time = { version = "0.3", features = [ "formatting" ] }
