[package]
name = "v5_core"
description = "Vex V5 robot serial port accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
btleplug = "0.11"
clap = "4"
crc = "3"
libloading = "0.8"
log = "0.4"
futures = "0.3"
serde = "1"
serialport = "4"
thiserror = "1.0"
time = { version = "0.3", features = [ "formatting" ] }
tokio = { version = "1.29", features = ["rt"] }
uuid = "1.4"
