[package]
name = "v5_core"
description = "Vex V5 robot serial port accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
chrono = "0.4"
crc = "3.0"
libloading = "0.7"
log = "0.4"
serde = "1.0"
serialport = "4.2"
tokio = { version = "1.22", features = [ "rt-multi-thread", "tokio-macros" ]}
