[package]
name = "v5_cli"
description = "Vex V5 robot serial port accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
v5_core = { path = "../core" }
v5_upload = { path = "../upload" }
v5_manage = { path = "../manage" }
v5_terminal = { path = "../terminal" }
env_logger = "0.10"
libloading = "0.7"
serialport = "4.2"
