[package]
name = "v5_upload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v5_core = { path = "../core" }
flate2 = "1.0"
md5 = "0.7"
