[package]
name = "v5_terminal"
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v5_core = { path = "../core" }
base85 = "1"
